### ISSUE TITLE
Kernel won't boot

### ISSUE THREAD

**Issue by floion** [andy-shev/linux#16]
Hi guys,
I am using git://github.com/htot/linux.git , branch eds-4.11 which should be pretty much the same kernel as the one from this repo.
However, the kernel won't boot. It just hangs at "Starting kernel ..." forever.
Has anybody seen this with this kernel?
I am currently building this repository here also and giving it a try also
Thanks

**Comment by floion** [comment]
Just tried with d88fa47004f0aa7f6290bc8b9665e356a1cd4f5b and I get the same thing

I have

> console=ttyMFD2 earlyprintk=ttyMFD2,keep loglevel=4

but there's nothing printed after "Starting kernel ..."

**Comment by floion** [comment]
@andy-shev have you ever seen this?

**Comment by AurelienBallier** [comment]
Use: console=tty1 console=ttyS2,115200n8 loglevel=7

**Comment by floion** [comment]
Thanks @AurelienBallier , I have eyes now :)
So the tty has changed for this kernel? I was expecting ttyMFD2 to be exposed as the console still. Doesn't matter too much if it is not exposed anymore.
I can now see the subsequent error. Time to fix the fstab

**Comment by AurelienBallier** [comment]
Yes serial interfaces have "standard" names now ttyS0, ttyS1 and ttyS2.

**Comment by floion** [comment]
I see, thanks for the info

**Comment by andy-shev** [comment]
Thank you @AurelienBallier for taking care about the issue. Closing as invalid based on help given.
