### ISSUE TITLE
unloading SDIO kernel module

### ISSUE THREAD

**Issue by farfromrefug** [andy-shev/linux#19]
Recently i stumble upon the issue where some Edison GPIOs where could not write on them because they were reserved for the SD:
https://communities.intel.com/thread/77677

I know i can compile a kernel without that module. But i would prefer to be able to unload /load it at runtime.
I don't enought about kernels to actually know where to look to see if this kernel allows this.
Can you guide me?

Thanks

**Comment by andy-shev** [comment]
So, the kernel allows user to *unload* module (means that *all* devices will be gone which are supported by the driver in question) if there is no active user (of *any* of them), or *unbind* certain device from the driver — condition is the same, no active user of it.
There is a good article to start with if you are interested in the latter mechanism https://lwn.net/Articles/143397/

**Comment by andy-shev** [comment]
@farfromrefug, is everything clarified?

**Comment by farfromrefug** [comment]
@andy-shev thanks yes it s  clear now

**Comment by andy-shev** [comment]
Closed based on comment from @farfromrefug.
