### ISSUE TITLE
thinkpad battery: force-discharge and inhibit-charge

### ISSUE THREAD

**Issue by dkwo** [andy-shev/linux#30]
These patches introduce support for

- force the battery to discharge when AC is attached
- hold battery charging via a manual override called Inhibit Charge

on Lenovo ThinkPads.

[1] https://gist.github.com/linrunner/31ab2f83c986e640ce8f7a4032d81a28
[2] https://gist.github.com/linrunner/5109b0ed2655fdcaf88a30a0303125bf
[3] https://gist.github.com/linrunner/fd07193578e07f16a5c1c9af3309f0d2

They have been tested and work.
Would it be possible to merge them?
Thanks.

**Comment by andy-shev** [comment]
Thanks for your contribution! The proper way to submit is to send to the platform-driver-x86@vger.kernel.org mailing list using `git format-patch ...; git send-email ...` tools. 
@jwrdegoede is on of the maintainers of the subsystem in the Linux kernel.
